### ISSUE TITLE
Use ISO 8601 datetime format for comments and Javadoc to unify used format and make it unambiguous

### ISSUE THREAD

**Issue by sceiler** [saucelabs/saucerest-java#100]
Definition of ISO 8601 (https://en.wikipedia.org/wiki/ISO_8601)

YYYY-MM-DD or YYYYMMDD
YYYY-MM-DDThh:mm:ssZ

**Example**
Date

- 2020-10-05

Date and time in UTC 

- 2020-10-05T15:49:24+00:00
- 2020-10-05T15:49:24Z
- 20201005T154924Z

**Reason for change**
Developers from all over the world might be working and using this library. As a result a datetime format standard should be in place for documentation and comments to avoid confusion. To solve this we should ISO 8601 as a standard.

**Comment by GuptaAkshay** [comment]
Hi @sceiler, I would Like to work on it.

**Comment by GuptaAkshay** [comment]
As per my understanding, we have to fix the date in java doc/comments to ISO 8601. Please, correct me if it differs?

**Comment by GuptaAkshay** [comment]
Hi @sceiler 
while executing `mvn clean install`  I am getting an error while generating java docs. Attached image below for reference.

![image](https://user-images.githubusercontent.com/8149016/95159402-97ae6680-07bb-11eb-9d2e-1d79ba2c1488.png)

**Comment by sceiler** [comment]
@GuptaAkshay I merged #101 into master. This should fix the error you are getting. Feel free to assign this issue to yourself and start working on it.

**Comment by GuptaAkshay** [comment]
@sceiler I think I do not have permission to assign the issue to myself or add a reviewer to this. I have raised a PR for the fix https://github.com/saucelabs/saucerest-java/pull/104
let me know if any changes required.

**Comment by enriquegh** [comment]
Fixed in #104
