### ISSUE TITLE
Please, add more API for Sauce Connect tunnels management

### ISSUE THREAD

**Issue by andrei-khveras** [saucelabs/saucerest-java#18]
Could you, please, enrich Sauce Connect tunnel management API (that currently represented by single getTunnels() method) by additional methods such as:
- getTunnel (String id) - to return SauceTunnel object
- findTunnel(String identifier) to find SauceTunnel object by tunnel Identifier (don't miss with ID)

**Comment by halkeye** [comment]
@andrei-khveras i know this is forever ago, but i'm slowly improving the library. Is there any downsides that you can think of to including the fasterxml library? can it break peoples installs and stuff?

**Comment by DylanLacey** [comment]
Closing; out of date.
