### ISSUE TITLE
Adding proxy details for Sauce rest Java

### ISSUE THREAD

**Issue by tamilmanam1** [saucelabs/saucerest-java#20]
Hi,

I am creating the saucerest client by proving the user name and access key. I would like to pass the proxy details also as part of the sauce rest client. Can you please let me know how to do that?

**Comment by rossrowe** [comment]
You can specify the proxy information by setting the following system properties:

            System.setProperty("http.proxyHost", proxyHost);
            System.setProperty("https.proxyHost", proxyHost);
            System.setProperty("http.proxyPort", proxyPort);
            System.setProperty("https.proxyPort", proxyPort);
            System.setProperty("http.proxyUser", userName);
            System.setProperty("https.proxyUser", userName);
            System.setProperty("http.proxyPassword", password);
            System.setProperty("https.proxyPassword", password);

These should be able to be set via command line arguments (eg. -Dhttp.proxyUser=...) or via code
