### ISSUE TITLE
getBuildJobs method is returning empty builds

### ISSUE THREAD

**Issue by madhusudhanmulkalapally** [saucelabs/saucerest-java#217]
I am trying to get the BuildJobs info by using sauce Rest API but I am not able to get the buildjob information, Please find the below mentioned code and please help me to resolve the issue.

SauceREST sauce = new SauceREST("provided my user name","provided my access key", DataCenter.EU);
String text = sauce.getBuildJobs(JobSource.VDC,"test");

I am using below mentioned dependency:
<dependency>
    <groupId>com.saucelabs</groupId>
    <artifactId>saucerest</artifactId>
    <version>1.1.0</version>
</dependency>

**Comment by sceiler** [comment]
Hi @madhusudhanmulkalapally,

please use our bug report template when raising issues so that all necessary information are captured. https://github.com/saucelabs/saucerest-java/issues/new?assignees=&labels=&template=bug_report.md&title=
