### ISSUE TITLE
getBuildJobs method is returning empty builds

### ISSUE THREAD

**Issue by madhusudhanmulkalapally** [saucelabs/saucerest-java#218]
## The problem

I am trying to get the BuildJobs info by using sauce Rest API but I am not able to get the buildjob information,

## Environment

* Java JDK version that exhibits the issue: jdk1.8.0_271
* saucerest-java version that exhibits the issue: 1.1.0
* Operating System / version that exhibits the issue: Windows10
* Last configuration (Java, saucerest-java, OS, OS version) that did not exhibit the issue (if applicable):

## Details

I am trying to download all the jobs related to particular build name by using sauce rest getBuildJobs method but I am not getting any jobs info. I have informed to the sauce lab teams support they told me that they were able to reproduce this issue. Please find below mentioned code I have used to get the job info.

SauceREST sauce = new SauceREST("provided my user name","provided my access key", DataCenter.EU);
String text = sauce.getBuildJobs(JobSource.VDC,"test");

## Link to logs

If your log files are really long consider creating a [GIST](https://gist.github.com) which is a paste of your _full_  logs, and link them here. Otherwise this report will be long and hard to read.

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by sceiler** [comment]
Can you please try version 2.x? I will close this for now but please create a new issue if you still see this in version 2.x
