### ISSUE TITLE
Sauce REST downloadVideo method is not working, throwing an exception and APi url also broken in the method 

### ISSUE THREAD

**Issue by madhusudhanmulkalapally** [saucelabs/saucerest-java#238]
When I try to download RDC vidoes by suing sauce rest method which is downloadVideo method, getting an error

**Comment by sceiler** [comment]
@madhusudhanmulkalapally please use the issue templates to raise issues. Furthermore, without more information or details we cannot reproduce the issue you are reporting. I am closing this issue the above mentioned reasons.
