### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by valfirst** [saucelabs/saucerest-java#327]
Please release a new version which will include the fix for blocker: https://github.com/saucelabs/saucerest-java/pull/314.

According to Sauce Labs Support:

> However, given that this is an open source project, it's advised that you should follow established open source guidelines which is typically using the available features of the platform where they are hosted. In this case GitHub. 
> 
> For example:
> If you are awaiting a new version of https://github.com/saucelabs/saucerest-java, you can open an Issue within that saucerest-java repo to inquire on when the next version may be released

**Comment by sceiler** [comment]
Please explain why 314 would be a blocker. In the PR you said it might introduce unexpected behavior. Please explain what unexpected behaviour and under what circumstances. Given the lack of further details it's impossible to determine the importance and urgency of this request.

**Comment by valfirst** [comment]
`junit-platform.properties` was put in the root of the class path, this file configures behavior of JUnit-based tests. Since the file was delivered as a part of `saucerest-java`, it affects all libraries/frameworks using this depdendency. 

`junit-platform.properties` from `saucerest-java` contains non-default JUnit connfguration, it leads to unexpected results, like, execution of tests in parallel. It's blocker because it's not possible t change the beahvior back easily and parallel execution is not possible for all our cases.

**Comment by sceiler** [comment]
Thank you. I will make a release now.

**Comment by valfirst** [comment]
@sceiler do you have any updates?

**Comment by sceiler** [comment]
No not yet. Unfortunately an int test is failing and I am currently looking into it. Wasnt able to last week.

**Comment by sceiler** [comment]
Release is done. 2.0.3 should propagate now and shortly be available.
