### ISSUE TITLE
BuildUtils.Java missing

### ISSUE THREAD

**Issue by nkalyanreddy** [saucelabs/saucerest-java#34]
Hi,

When I tried to integrate the SauceRest library into my framework, I am getting error on source SaueRest.java at line number 129, the error is "cannot resolve symbol BuildUtils". I am guessing this is because the BuildUtils class is missing. can you please look into this. Thanks you.

Regards,
-Kalyan.

**Comment by halkeye** [comment]
Hi Kalyan,

I'm actually out of the office this week so I can't confirm but I'm 99% sure it's a file generated by one of the maven steps.

Have you tried mvn compile?

**Comment by nkalyanreddy** [comment]
Hi Gavin,

Thanks for very quick response. No not tried compile. I will try that.

Thanks again.

Regards,
-Kalyan.

**Comment by halkeye** [comment]
Did that work? Can I close this?

**Comment by nkalyanreddy** [comment]
Yes on compiling the project BuildUtils.java is generated. Thanks for quick response once gain.

**Comment by nkalyanreddy** [comment]
Hi Gain,

I have commented and closed the ticket. Thanks.

Regards,
-Kalyan.
