### ISSUE TITLE
Exception while retrieving UploadFileApp from uploadFile

### ISSUE THREAD

**Issue by OmkarTrivediLss** [saucelabs/saucerest-java#393]
## The problem

While uploading file, file is being uploaded successfully but on response getting "Cannot skip unexpected NAME at $.item.metadata.icon_hash".

## Environment

* Java JDK version that exhibits the issue: 1.8
* saucerest-java version that exhibits the issue: 2.0.5
* Operating System / version that exhibits the issue: MacOS Monterey 12.6.2
* Last configuration (Java, saucerest-java, OS, OS version) that did not exhibit the issue (if applicable):

## Details

Functionality was working fine before a week i guess.

## Link to logs

If your log files are really long consider creating a [GIST](https://gist.github.com) which is a paste of your _full_  logs, and link them here. Otherwise this report will be long and hard to read.

## Code To Reproduce Issue [ Good To Have ]

Use sauceREST.getStorage().uploadFile() method to upload .apk file and observe.

**Comment by sceiler** [comment]
Thanks for the report! I have an idea what is the cause of this and will fix soon. I believe the exception being thrown shouldn't affect the use too much.

**Comment by OmkarTrivediLss** [comment]
Thanks for your quick response. Since file is being uploaded, we're not blocked at all but as we can not get storage id of the file, it may require lil bit of manual work.

**Comment by sceiler** [comment]
Did you build the jar yourself and you still see the issue? I haven't released a new version with the fixes to Maven yet though.

**Comment by OmkarTrivediLss** [comment]
Oh my bad! I will check and verify. Thanks.

**Comment by OmkarTrivediLss** [comment]
I have tried to build jar (skipped tests) from master branch, getting this...

<img width="1728" alt="Screenshot 2023-06-22 at 21 08 43" src="https://github.com/saucelabs/saucerest-java/assets/69293808/9981985a-073b-41f6-8afd-f97e952d91eb">

 Is branch next version stable?

**Comment by sceiler** [comment]
No next-version is a development branch.

Try to run this command:
`run: mvn clean test -Dtest="com.saucelabs.saucerest.unit.**" -Dgpg.skip -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -V`
The error you see is because you don't have the right setup to also sign the jar which is needed in our case because of releasing it to maven central.
