### ISSUE TITLE
Exception while getting rdc job status

### ISSUE THREAD

**Issue by OmkarTrivediLss** [saucelabs/saucerest-java#395]
## The problem

While retrieving rdc job status for specific device getting an exception 'Cannot skip unexpected NAME at $.backtrace_url'.

## Environment

* Java JDK version that exhibits the issue: 1.8
* saucerest-java version that exhibits the issue: 2.0.5
* Operating System / version that exhibits the issue: MacOS Monterey 12.6.2
* Last configuration (Java, saucerest-java, OS, OS version) that did not exhibit the issue (if applicable):

## Details

Able to repro issue from last 2-3 days. 

## Link to logs

If your log files are really long consider creating a [GIST](https://gist.github.com) which is a paste of your _full_  logs, and link them here. Otherwise this report will be long and hard to read.

## Code To Reproduce Issue [ Good To Have ]

Use sauceREST.getRealDevices().getSpecificDeviceJob() method and try to fetch status.

**Comment by sceiler** [comment]
Thanks. Should be fixed with #394
