### ISSUE TITLE
Support new US East 4 endpoint

### ISSUE THREAD

**Issue by alexh-sauce** [saucelabs/saucerest-java#428]
https://github.com/saucelabs/saucerest-java/blob/master/src/main/java/com/saucelabs/saucerest/DataCenter.java#L5

The new US East 4 datacenter is not supported.

**Comment by diemol** [comment]
I think we should add this when all services are supported, and when customers request this. In any case, users can create a `DataCenter` object with the required information and use it when instantiating `SauceREST`.
