### ISSUE TITLE
get har file

### ISSUE THREAD

**Issue by romainlouvet** [saucelabs/saucerest-java#54]
is-it possible to get .har with saucerest service ?

https://wiki.saucelabs.com/pages/viewpage.action?pageId=70072943

**Comment by DylanLacey** [comment]
It will be once this PR is merged and a new release cut: https://github.com/saucelabs/saucerest-java/pull/50

**Comment by romainlouvet** [comment]
ok thanks @DylanLacey !
I just tested the last snaphot but 
downloadHAR("d3ea050f29af45b6918b6aac78129683", "/var/tmp/HAR.log");
->
java.io.FileNotFoundException: https://saucelabs.com/rest/v1/rlouvet/jobs/d3ea050f29af45b6918b6aac78129683/assets/network.har
while extended debug capabilities is enable and visible with saucelabs website
