### ISSUE TITLE
File not found download file

### ISSUE THREAD

**Issue by romainlouvet** [saucelabs/saucerest-java#56]
I just tested the last snaphot (1.0.38-SNAPSHOT) but
downloadHAR("31631287702d4e418624f8a58cd24397", "/var/tmp/HAR.log");
->
java.io.FileNotFoundException: https://saucelabs.com/rest/v1/rlouvet/jobs/31631287702d4e418624f8a58cd24397/assets/network.har
while extended debug capabilities is enable and visible with saucelabs website

same problem with downloadLog (1.0.37)

here my Job Info: {"browser_short_version": "60", "video_url": "https://saucelabs.com/jobs/31631287702d4e418624f8a58cd24397/video.flv", "creation_time": 1526544496, "custom-data": null, "browser_version": "60.0.3112.78", "owner": "rlouvet", "automation_backend": "webdriver", "id": "31631287702d4e418624f8a58cd24397", "collects_automator_log": false, "record_screenshots": true, "record_video": true, "build": "build-null", "passed": true, "public": "team", "assigned_tunnel_id": null, "status": "in progress", "log_url": "https://saucelabs.com/jobs/31631287702d4e418624f8a58cd24397/selenium-server.log", "start_time": 1526544497, "proxied": false, "modification_time": 1526544525, "tags": ["Tag1"], "name": null, "commands_not_successful": 0, "video_secret": "a2322b77d8ec47618776f748e6fd0294", "consolidated_status": "passed", "selenium_version": null, "manual": false, "end_time": null, "error": null, "os": "Windows 10", "breakpointed": null, "browser": "googlechrome"}

**Comment by DylanLacey** [comment]
Hmm.  It looks like the REST API is returning a not authorised method for HAR files.  I'm not sure why, but I've opened a ticket internally (I work for Sauce Labs, but I'm not on the team responsible for the REST API).

downloadLog failing is a bit weirder.  I'm able to make use of it.  Had you already closed your job before attempting to download the log?  After a job is closed, we prepare and store assets, and until that process is completed, they're not available through the REST API.  The longer your job ran, the longer this process can take.

**Comment by DylanLacey** [comment]
This is partly fixed by #64.  I added a feature request, #58, asking for retry logic (I don't have the ability to add it right now).

Can you give the latest a go and see if it's helpful?

**Comment by romainlouvet** [comment]
afterjava.io.FileNotFoundException: /var/tmp/HAR.log/70dd459e7ddd4524b3edc5e56363fda720180518_0907529.log (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)

**Comment by DylanLacey** [comment]
There's something up with that jobId; It's not valid.  70dd459e7ddd4524b3edc5e56363fda720180518 is a valid ID, but not with the underscore.  Hmm.  What's the value of JobId there?

**Comment by romainlouvet** [comment]
with another job
java.io.FileNotFoundException: /var/tmp/HAR.log/65b5e8b77ea2403bb8f8816f1108b16820180522_0920347.log (No such file or directory)

**Comment by javydreamercsw** [comment]
Running into the same issue.

**Comment by enriquegh** [comment]
@romainlouvet @javydreamercsw are you still seeing this issue with 1.0.44?

for the downloadX methods the location passed must be the directory where the file is going to be saved and must not include the .log or .har file.
An example is:

```java
downloadHAR(jobId, "/var/tmp/");
```

another recommendation is to wait a small amount of time between the driver.quit() and trying to get the assets since depending on the size of them the upload procedure might take a while.

Give that a try and let us if that helps.

**Comment by javydreamercsw** [comment]
I have to try not adding the file name at the end but waiting extra time after closing the driver isn't working for me.

**Comment by enriquegh** [comment]
After https://github.com/saucelabs/saucerest-java/pull/87 all issues with files should be fixed.
If you're still having trouble please open a Support ticket at help@saucelabs.com.
