### ISSUE TITLE
Check whether a job has finished before fetching assets

### ISSUE THREAD

**Issue by DylanLacey** [saucelabs/saucerest-java#59]
As per #58, asset fetching can fail if done too soon after a job completes.  Because Sauce Labs does asset finalisation during job finalisation, it may be possible to check the job status using the REST API, before attempting to fetch an asset.

This could be part of the retry logic, or its own standalone feature that just raises an exception when assets aren't yet ready.

**Comment by Valeriia-Savinova** [comment]
Hi Dylan, are there any updates on that? 
Would be great to have this feature 👍
