### ISSUE TITLE
Timeout errors when posting a bigger app file

### ISSUE THREAD

**Issue by schwarcu** [saucelabs/saucerest-java#67]
Example: 13.3MB iOS app.
Unable to post file using uploadFile()
 due to timeout error.

**_`java.net.SocketTimeoutException: Read timed out`_**

![saucerest](https://user-images.githubusercontent.com/31127747/41582944-49406786-73a3-11e8-9d11-0f9b5129f6ab.PNG)

**Comment by archick12** [comment]
Same issue.
