### ISSUE TITLE
Can't access to har

### ISSUE THREAD

**Issue by romainlouvet** [saucelabs/saucerest-java#80]
since 1 week we can't access to har file

sauce.getHARDataStream(jobId);

->
java.io.FileNotFoundException: https://eu-central-1.saucelabs.com/rest/v1/lbc_france/jobs/d21a9a247f254a00927f260201a93793/assets/network.har

version 1.0.44

from saucelabs website I can access to network panel (https://eds.eu-central-1.saucelabs.com/d21a9a247f254a00927f260201a93793/network.har)

**Comment by javydreamercsw** [comment]
Seems to be a duplicate of #56.

**Comment by enriquegh** [comment]
Duplicate of #56
