### ISSUE TITLE
downloadVideoOrThrow(id, location) doesn't exist in 1.0.44

### ISSUE THREAD

**Issue by kyleshrader** [saucelabs/saucerest-java#91]
The README.md says that a downloadVideoOrThrow method is available, but I am not seeing it in 1.0.44. This method would be useful.

**Comment by DylanLacey** [comment]
It looks like the PR for `downloadVideoOrThrow` was merged after the 1.0.44 release, so the README is a little out of date.  This repo is getting a lot of activity from Hacktoberfest and Sauce have recently established an Open Source Program Office internally, so should be cutting a new release soon.

(I can send PRs, but don't have the ability to cut a release on Sauce's behalf).

(We're also _maybe_ changing the method name: https://github.com/saucelabs/saucerest-java/issues/107)

**Comment by sceiler** [comment]
Closing as not applicable anymore.
