### ISSUE TITLE
Har file download 

### ISSUE THREAD

**Issue by code255255** [saucelabs/saucerest-java#93]
Hi,
 Hi,
I'm using below method to download the har file after completion of selenium script.
sauce.downloadHAR("job_id", "/var/tmp/");

I see the log file is downloaded instead har, can you please check?
attached log file for reference.

[ec9a340e71534193a6f0f670356e7bff20200812_1022270.log](https://github.com/saucelabs/saucerest-java/files/5064939/ec9a340e71534193a6f0f670356e7bff20200812_1022270.log)

**Comment by code255255** [comment]
Any update on this?

**Comment by sceiler** [comment]
@code255255 
I am trying to reproduce this issue but so far it has been working with version 1.0.44 for me. Do you have a minimal working code example you can share? Does this issue still happen to you?
