### ISSUE TITLE
Fix javadoc generating warning and errors

### ISSUE THREAD

**Issue by sceiler** [saucelabs/saucerest-java#99]
When running `mvn clean install` or more specifically `mvn org.apache.maven.plugins:maven-javadoc-plugin:3.1.0:jar` it will fail with this error:

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  8.089 s
> [INFO] Finished at: 2020-10-05T17:51:57+02:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.0:jar (default-cli) on project saucerest: MavenReportException: Error while generating Javadoc:
> [ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
> [ERROR] /Users/yimin.yang/Documents/Github/saucerest-java/src/main/java/com/saucelabs/saucerest/SauceException.java:13: warning: no @param for message
> [ERROR]     public SauceException(String message) {
> [ERROR]            ^
> [ERROR] /Users/yimin.yang/Documents/Github/saucerest-java/src/main/java/com/saucelabs/saucerest/SauceREST.java:203: warning: no @param for endpoint
> [ERROR]     protected URL buildEDSURL(String endpoint) {
> [ERROR]                   ^
> [ERROR] /Users/yimin.yang/Documents/Github/saucerest-java/src/main/java/com/saucelabs/saucerest/SauceREST.java:332: error: no tag name after @
> [ERROR]      * @// TODO: 27/2/20 I think this should be called "downloadVideo" and "attemptVideoDownload" should be the silent failure method - Dylan
> [ERROR]        ^
> [ERROR] /Users/yimin.yang/Documents/Github/saucerest-java/src/main/java/com/saucelabs/saucerest/SauceREST.java:366: error: no tag name after @
> [ERROR]      * @// TODO: 27/2/20 I think this should be called "attemptLogDownload" - Dylan
> [ERROR]        ^
> [ERROR] /Users/yimin.yang/Documents/Github/saucerest-java/src/main/java/com/saucelabs/saucerest/SauceREST.java:382: error: no tag name after @
> [ERROR]      * @// TODO: 27/2/20 I think this should be called "downloadLog" and "attemptLogDownload" should be the silent failure method - Dylan
> [ERROR]        ^
> [ERROR] /Users/yimin.yang/Documents/Github/saucerest-java/src/main/java/com/saucelabs/saucerest/SauceREST.java:411: error: no tag name after @
> [ERROR]      * @// TODO: 27/2/20 I think this should be renamed "attemptHARDownload" - Dylan
> [ERROR]        ^
> [ERROR] /Users/yimin.yang/Documents/Github/saucerest-java/src/main/java/com/saucelabs/saucerest/SauceREST.java:430: error: no tag name after @
> [ERROR]      * @// TODO: 27/2/20 I think this should be called "downloadHAR" and attemptHARDownload should be the silent failure method - Dylan
> [ERROR]        ^
> [ERROR]
> [ERROR] Command line was: /Library/Java/JavaVirtualMachines/openjdk-14.0.1.jdk/Contents/Home/bin/javadoc @options @packages
> [ERROR]
> [ERROR] Refer to the generated Javadoc files in '/Users/yimin.yang/Documents/Github/saucerest-java/target/apidocs' dir.
> [ERROR]
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Fix is to add/edit Javadoc as shown in the error.

**Comment by basalt79** [comment]
@sceiler  i will give it a try

**Comment by sceiler** [comment]
Fixed with #101
